### ISSUE TITLE
Build fails with issue between java and kotlin

### ISSUE THREAD

**Issue by martijn00** [nfcim/flutter_nfc_kit#127] opened 2023-11-01 13:26 UTC
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_nfc_kit:compileDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (11) and 'compileDebugKotlin' (17).

**Comment by Harry-Chen** [comment] 2023-11-01 14:07
Maybe try higher JDK version like 17?

**Comment by martijn00** [comment] 2023-11-01 14:24
No that doesn't work and gives the same error. @mvanbeusekom you looked at this before. Can you give any hints?

**Comment by Harry-Chen** [comment] 2023-11-01 14:31
In flutter_nfc_kit, `sourceCompatibility` was set to 11:

https://github.com/nfcim/flutter_nfc_kit/blob/cc5c098700e618ba5629dbc33a00fce1cae12863/android/build.gradle#L22-L25

Would it be some other dependency that causes the problem?

**Comment by martijn00** [comment] 2023-11-01 15:13
Would it be possible to set it to VERSION_17?

**Comment by Harry-Chen** [comment] 2023-11-01 15:16
>  tasks 'compileDebugJavaWithJavac' (11) and 'compileDebugKotlin' (17).

Please note that the version 11 does not come from our project since we have no Java code at all. Maybe you should check other dependencies, or at least provide a minimal project that can reproduce this problem.

**Comment by martijn00** [comment] 2023-11-01 15:21
What about: https://github.com/flutter/packages/blob/main/packages/webview_flutter/webview_flutter_android/android/build.gradle#L26

And why not set it to VERSION_1_8 like the official Flutter plugins:
https://github.com/flutter/packages/blob/main/packages/webview_flutter/webview_flutter_android/android/build.gradle#L51

**Comment by martijn00** [comment] 2023-11-01 15:23
Here: https://github.com/nfcim/flutter_nfc_kit/blob/cc5c098700e618ba5629dbc33a00fce1cae12863/android/gradle/wrapper/gradle-wrapper.properties#L4

I use: https\://services.gradle.org/distributions/gradle-8.3-all.zip

**Comment by AristideVB** [comment] 2024-03-13 19:41
@Harry-Chen You should indeed set it to 17, see similar issue on other package https://github.com/matanshukry/flutter_google_places_sdk/issues/71

**Comment by Harry-Chen** [comment] 2024-04-04 12:31
Fixed in version 3.5.0.

**Closed by Harry-Chen** 2024-04-04 12:31 UTC

**Comment by luckycreationsindia** [comment] 2024-07-19 09:51
> Here:
> 
> https://github.com/nfcim/flutter_nfc_kit/blob/cc5c098700e618ba5629dbc33a00fce1cae12863/android/gradle/wrapper/gradle-wrapper.properties#L4
> 
> I use: https://services.gradle.org/distributions/gradle-8.3-all.zip

Facing this issue with latest flutter version with gradle 8+

Note:
I'm using gradle 8.7 due to compatibility issue with latest flutter version
